eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
spring:
  application:
    name: springcloud-study-ribbon
  zipkin:
    base-url: http://localhost:8760
server:
  port: 8763