eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
spring:
  application:
    name: springcloud-study-feign
server:
  port: 8767
feign:
  hystrix:
    enabled: true