eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
turbine:
  app-config: springcloud-study-ribbon-hystrix  # serviceId列表
  cluster-name-expression: new String("default") #clusterNameExpression指定集群名称
  combine-host-port: true
spring:
  application:
    name: springcloud-study-hystrix-turbine
server:
  port: 8769