eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
spring:
  application:
    name: springcloud-study-zuul
server:
  port: 8765
zuul:
  routes:
    study-feign :
      path: /study-feign/**
      serviceId: springcloud-study-feign
    study-client :
      path: /study-client/**
      serviceId: springcloud-study-client