eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
spring:
  application:
    name: springcloud-study-zuul
server:
  port: 8765
zuul:
  routes:
    hello-a :
      path: /hello-a/**
      serviceId: springcloud-study-feign